'use client';
import { useEffect, useState, useRef } from 'react';
import { Crosshair, Orbit, Compass, Package, Radio, Shield, ChevronRight, Volume2, VolumeX, Pause, Play, CircleHelp, ArrowUpRight, Anchor, Navigation, ScanLine, Zap, Map, Rocket } from 'lucide-react';
import { Universe, SYSTEMS, distance, STATION } from './engine';
import SpaceView from './SpaceView';
import { GalaxyMap, StationPanel, CargoPanel, LogPanel, FlightManual } from './Panels';
import { registerGameTools } from './webmcp';

export default function Game(){
 const [game]=useState(()=>new Universe());const [,render]=useState(0);const refresh=()=>render(v=>v+1);
 const [tab,setTab]=useState('flight');const [muted,setMuted]=useState(true);const [paused,setPaused]=useState(false);const [help,setHelp]=useState(false);const [rescued,setRescued]=useState(false);
 const uiRef=useRef({tab,help,paused,muted});uiRef.current={tab,help,paused,muted};const audioRef=useRef<AudioContext|null>(null);
 const closePanel=()=>{if(game.jump!==null)setPaused(false);if(game.docked){setTab('station');}else setTab('flight');};
 const closeStation=()=>{game.undock();setTab('flight');};
 const toggleAudio=()=>{if(!audioRef.current)audioRef.current=new AudioContext();void audioRef.current.resume();setMuted(v=>!v);};
 useEffect(()=>{game.paused=paused||help||['map','cargo','log'].includes(tab)||rescued;game.keys.clear();},[game,paused,help,tab,rescued]);
 useEffect(()=>{const saved=Universe.restore();if(saved){game.s=saved;game.populate();game.notify('Flight record restored. Welcome back, Captain.');}game.onChange=refresh;game.onDock=()=>setTab('station');game.onRescue=()=>{setTab('station');setRescued(true);};game.onSound=(type)=>{const ctx=audioRef.current;if(!ctx||uiRef.current.muted)return;const oscillator=ctx.createOscillator(),gain=ctx.createGain();const frequencies:Record<string,number[]>={fire:[540,130],hit:[95,35],explode:[75,20],trade:[520,880],dock:[190,380],jump:[70,750]};const [from,to]=frequencies[type]??[240,120];const duration=type==='jump'?1.8:type==='explode'?.6:type==='trade'?.18:.12;oscillator.type=type==='explode'||type==='fire'?'sawtooth':'sine';oscillator.frequency.setValueAtTime(from,ctx.currentTime);oscillator.frequency.exponentialRampToValueAtTime(to,ctx.currentTime+duration);gain.gain.setValueAtTime(type==='fire'?.025:.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+duration);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};};
 const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,select,textarea')||e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(key==='escape'&&!e.repeat){if(uiRef.current.help)setHelp(false);else if(uiRef.current.tab==='station'){game.undock();setTab('flight');}else if(uiRef.current.tab!=='flight')setTab(game.docked?'station':'flight');else setPaused(v=>!v);return;}if(key==='m'&&!e.repeat){setTab(v=>v==='map'?(game.docked?'station':'flight'):'map');return;}if(key==='?'&&!e.repeat){setHelp(v=>!v);return;}if(uiRef.current.tab!=='flight'||uiRef.current.help||uiRef.current.paused)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','shift'].includes(key)){e.preventDefault();game.keys.add(key);}if(e.repeat)return;if(key==='t')game.cycle();if(key==='e')game.dock();};
 const up=(e:KeyboardEvent)=>game.keys.delete(e.key.toLowerCase());const blur=()=>game.keys.clear();const visibility=()=>{if(document.hidden){game.keys.clear();setPaused(true);}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);const save=setInterval(()=>game.save(),5000);const unregister=registerGameTools(game,refresh);
 return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);clearInterval(save);unregister();game.save();};},[game]);
 const s=game.s,sys=SYSTEMS[s.system],stats=game.stats,selected=game.selected;
 return <main className="game-shell">
  <header className="topbar"><div className="brand"><Orbit size={30}/><div>VOIDWAKE<small>THE OUTER REACH</small></div><span className="alpha">SANDBOX</span></div><nav>{[['flight','Flight deck',Navigation],['map','Galaxy map',Map],['cargo','Cargo hold',Package],['log','Captain’s log',Compass]].map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id==='flight'&&game.docked?'station':id as string)} key={id as string}>{typeof Icon!=='string'&&<Icon size={17}/>}<span>{label as string}</span></button>)}</nav><div className="top-actions"><span className="live-dot"/> <span className="save-label">LOCAL SAVE</span><button title={muted?'Enable sound':'Mute sound'} aria-label={muted?'Enable sound':'Mute sound'} onClick={toggleAudio}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><button title="Pause" aria-label="Pause game" onClick={()=>{setPaused(!paused);}}>{paused?<Play size={18}/>:<Pause size={18}/>}</button><button aria-label="Flight manual" onClick={()=>setHelp(true)}><CircleHelp size={18}/></button></div></header>
  <div className="flight-layout"><aside className="left-panel"><div className="eyebrow">CURRENT SYSTEM <span>{String(s.system+1).padStart(2,'0')} / 07</span></div><div className="system-title"><h1>{sys.name}</h1><ArrowUpRight size={25}/></div><p className="system-region">{sys.region}</p><div className="faction"><span className="live-dot"/>{sys.faction}<span>{sys.security}</span></div><div className="panel-rule"/>
  <div className="section-title"><span>LOCAL CONTACTS</span><span>{game.contacts.length.toString().padStart(2,'0')}</span></div><div className="contact-list">{game.contacts.filter(c=>c.kind!=='salvage').map(c=><button key={c.id} onClick={()=>{game.target=c.id;refresh();}} className={`contact ${game.target===c.id?'selected':''} ${c.kind}`}><span className="contact-icon">{c.kind==='station'?<Orbit size={20}/>:c.kind==='hostile'?<Crosshair size={19}/>:<Navigation size={18}/>}</span><span><strong>{c.name}</strong><small>{c.kind==='station'?'Trading station':c.kind==='hostile'?'Hostile · pirate':c.kind==='patrol'?'Union patrol':'Civilian trader'}</small></span><em>{(distance(c,s)/1000).toFixed(1)}<small>km</small></em></button>)}</div>
  <div className="left-bottom"><div className="section-title"><span>FIRST FLIGHT</span><Compass size={15}/></div><h3>Make your own way.</h3><p>Dock at {sys.station} to trade, take a contract, or outfit your ship.</p><button className="text-button" onClick={()=>game.dock()}>Approach station <ArrowUpRight size={16}/></button></div></aside>
  <section className="viewport"><SpaceView game={game} onTick={refresh}/><div className="view-top"><span><span className="live-dot"/> FLIGHT ASSIST ONLINE</span><span>SECTOR {String(s.system+1).padStart(2,'0')} : {Math.round(s.x)} / {Math.round(s.y)}</span></div><div className="system-watermark">{sys.name}<small>{sys.kind} system</small></div><div className="view-tools"><button title="Zoom in" aria-label="Zoom in" onClick={()=>game.zoom=Math.min(1.8,game.zoom+.15)}>+</button><span>{Math.round(game.zoom*100)}%</span><button title="Zoom out" aria-label="Zoom out" onClick={()=>game.zoom=Math.max(.5,game.zoom-.15)}>−</button></div>
  <div className="view-bottom"><div className="telemetry"><span><i/> {game.docked?'DOCKED':game.waypoint?'AUTOPILOT ENGAGED':'FREE FLIGHT'}</span><strong>{Math.round(Math.hypot(s.vx,s.vy))}<small>m/s</small></strong><div className="speed-line"><span style={{width:`${Math.min(100,Math.hypot(s.vx,s.vy)/stats.speed*100)}%`}}/></div></div><div className="nav-hint"><kbd>W</kbd> thrust <kbd>A</kbd><kbd>D</kbd> steer <kbd>S</kbd> brake <span>·</span> Click space to fly</div></div>
  {game.messageTime>0&&<div className={`transmission ${game.toastKind}`} role="status"><Radio size={16}/><span>{game.message}</span></div>}
  {paused&&<div className="center-overlay"><Pause size={30}/><h2>Flight paused</h2><button className="primary" onClick={()=>{game.paused=false;setPaused(false);}}>Resume flight</button></div>}
  {tab==='map'&&<GalaxyMap game={game} close={closePanel}/>}
  {tab==='station'&&game.docked&&<StationPanel game={game} close={closeStation}/>}
  {tab==='cargo'&&<CargoPanel game={game} close={closePanel}/>}
  {tab==='log'&&<LogPanel game={game} close={closePanel}/>}
  {help&&<FlightManual game={game} close={()=>setHelp(false)}/>}
  {rescued&&<div className="center-overlay rescue"><Shield size={32}/><h2>Your escape pod was recovered.</h2><p>Your ship has been restored at the station.<br/>You lost your cargo and 10% of your credits.</p><button className="primary" onClick={()=>setRescued(false)}>Return to the station</button></div>}
  {game.jump!==null&&<div className="jump-overlay"><div className="jump-lines"/><Zap size={32}/><span>JUMP DRIVE ENGAGED</span><h2>{SYSTEMS[game.jump].name}</h2><p>Entering hyperspace in {Math.ceil(game.jumpTime)}…</p></div>}
  {tab==='flight'&&!help&&!paused&&<div className="touch-controls">{[['a','↶'],['w','↑'],['d','↷'],['s','↓'],['fire','◎']].map(([key,label])=><button key={key} aria-label={key==='fire'?'Fire weapons':key==='w'?'Thrust':key==='s'?'Brake':key==='a'?'Turn left':'Turn right'} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);game.keys.add(key);}} onPointerUp={()=>game.keys.delete(key)} onPointerCancel={()=>game.keys.delete(key)}>{label}</button>)}<button aria-label="Dock at station" onClick={()=>game.dock()}>E</button></div>}
  </section>
  <aside className="right-panel"><div className="section-title"><span>YOUR VESSEL</span><span className="online">● ONLINE</span></div><div className="vessel-id"><Rocket size={35}/><div><h2>{stats.name}</h2><p>{stats.role} <span>CV–001</span></p></div></div><div className="ship-status">{[['Hull integrity',s.hull,stats.hull,'hull'],['Shield array',s.shield,stats.shield,'shield'],['Reactor output',s.energy,100,'energy']].map(([label,value,max,name])=><div className={`meter ${name}`} key={name as string}><div><span>{label}</span><strong>{Math.round(Number(value)/Number(max)*100)}<small>%</small></strong></div><div className="bar"><i style={{width:`${Number(value)/Number(max)*100}%`}}/></div></div>)}</div><div className="resources"><div><span>AVAILABLE CREDITS</span><strong>{s.credits.toLocaleString()}<small>cr</small></strong></div><div><span>JUMP FUEL</span><strong>{Math.floor(s.fuel)}<small>/ 100</small></strong></div></div><div className="cargo-capacity"><Package size={16}/><span>Cargo hold</span><strong>{game.usedCargo} / {stats.cargo} t</strong></div><div className="panel-rule"/>
  <div className="section-title"><span>TARGET SCANNER</span><ScanLine size={15}/></div>{selected?<div className="target-card"><div className={`target-type ${selected.kind}`}>{selected.kind==='hostile'?'HOSTILE CONTACT':selected.kind==='station'?'STATION · FRIENDLY':'NEUTRAL CONTACT'}</div><h3>{selected.name}</h3><div className="target-distance"><span>Distance</span><strong>{Math.round(distance(selected,s))} m</strong></div><div className="target-distance"><span>Hull</span><strong>{Math.round(selected.hull)} / {selected.maxHull}</strong></div><button className={selected.kind==='hostile'?'danger':'primary'} onClick={()=>selected.kind==='station'?game.dock():selected.kind==='hostile'?game.fire():(game.waypoint={x:selected.x,y:selected.y})}>{selected.kind==='station'?<Anchor size={16}/>:<Crosshair size={16}/>} {selected.kind==='station'?(game.nearby?'Dock at station':'Approach & dock'):selected.kind==='hostile'?'Fire weapons':'Set intercept course'}<kbd>{selected.kind==='station'?'E':'SPACE'}</kbd></button></div>:<p className="muted">Select a contact to scan.</p>}
  <div className="radar-section"><div className="section-title"><span>TACTICAL RADAR</span><span>3 KM</span></div><div className="radar"><svg viewBox="0 0 220 150" aria-label="Tactical radar"><g fill="none" stroke="#244451" strokeWidth=".65"><ellipse cx="110" cy="75" rx="95" ry="65"/><ellipse cx="110" cy="75" rx="62" ry="42"/><ellipse cx="110" cy="75" rx="30" ry="20"/><path d="M15 75h190M110 10v130"/></g>{game.contacts.map(c=><circle key={c.id} cx={110+(c.x-s.x)/22} cy={75-(c.y-s.y)/22} r={c.kind==='station'?3:2} fill={c.kind==='hostile'?'#ed8e7c':c.kind==='station'?'#83cfc6':'#6c8ea2'}/>)}<path d="m110 70 4 9-4-2-4 2Z" fill="#d8f5ff"/></svg><span>LONG-RANGE SENSORS ACTIVE</span></div></div></aside></div>
  <footer><span><span className="live-dot"/> ALL SYSTEMS NOMINAL</span><div><span><kbd>SPACE</kbd> Fire weapons</span><span><kbd>T</kbd> Cycle target</span><span><kbd>SHIFT</kbd> Boost</span><button onClick={()=>setHelp(true)}><kbd>?</kbd> Flight manual</button></div><span>STARDATE 2486.{String(Math.floor(s.time/60)+1).padStart(3,'0')}</span></footer>
 </main>;
}
