'use client';
import { Radio,Navigation,Crosshair,Orbit,Shield,Package,ScanLine,Fuel,HeartPulse,Gem,ArrowUpRight } from 'lucide-react';
import { Universe,SYSTEMS,FACTIONS,GOODS,SHIPS,WEAPONS,factionIds,distance,fleetFor } from './engine';
import { PanelHeader } from './Panels';
import FactionFlag from './FactionFlag';
import ShipPortrait from './ShipPortrait';
import CaptainPortrait from './CaptainPortrait';

export function FactionPanel({game,close}:{game:Universe;close:()=>void}){
 return <div className="workspace-overlay diplomacy-workspace"><PanelHeader eyebrow="DIPLOMACY" title="The six powers" close={close}/><div className="standing-legend"><span>Allied ≥ 50</span><span>Neutral 0–49</span><span>Hostile &lt; 0</span></div><div className="faction-grid">{factionIds.map(id=>{const f=FACTIONS[id],standing=game.standing(id),relation=game.relation(id);return <article className="faction-card" key={id} style={{'--faction-color':f.color} as React.CSSProperties}><div className="faction-heading"><FactionFlag faction={id} large/><div><h3>{f.name}</h3><span>{f.capital} · {SYSTEMS.filter(s=>game.owner(s.id)===id).length} systems</span></div></div><div className={`faction-standing ${relation.toLowerCase()}`}><strong>{standing}</strong><span>{relation}</span><div><i style={{width:`${(standing+100)/2}%`}}/></div></div><p>{f.doctrine}</p><div className="fleet-names">{fleetFor(id).map(ship=><span key={ship}>{SHIPS[ship].name}</span>)}</div><div className="diplomatic-access"><Shield size={15}/>{standing<0?'Ports closed · patrols attack on sight':standing>=50?'Capital ships and advanced hulls unlocked':'Civilian and frigate hulls available'}</div></article>;})}</div><div className="rules-strip"><span>Unprovoked attack <b>−12</b></span><span>Civilian destroyed <b>−30</b></span><span>Medical aid <b>+8</b></span><span>Contract <b>+5</b></span><span>Survey / pirate <b>+2</b></span></div></div>;
}

export function InteractionPanel({game,close}:{game:Universe;close:()=>void}){
 const c=game.interactionContact;if(!c)return null;
 const faction=c.faction??game.faction,f=FACTIONS[faction],world=game.worlds.find(w=>w.id===c.id),dist=distance(game.s,c),hostile=game.isHostile(c),incident=game.s.incidents?.[game.s.system];
 const inOrbit=!!world&&dist<=world.radius+350,surveyRange=!!world&&dist<=world.radius+500;
 const approach=()=>{game.waypoint={x:c.x+(world?world.radius+160:0),y:c.y};game.autoDock=false;close();};
 const dock=()=>{close();game.dock();};
 const stock=c.quantity??0,good=c.good??0,buyPrice=Math.floor(game.price[good]*1.08);
 const refusing=c.provoked||game.alert||game.standing(faction)<0;
 const cooldown=world?Math.ceil(Math.max(0,(game.s.harvested?.[world.id]??-1e6)+120-game.s.time)):0;
 return <div className="workspace-overlay interaction-workspace"><PanelHeader eyebrow={world?'PLANETARY COMMUNICATIONS':c.kind==='station'?'PORT AUTHORITY':'SHIP COMMUNICATIONS'} title={c.name} close={close}/><div className="comms-faction"><FactionFlag faction={faction}/><span>{c.kind==='hostile'?'Unaffiliated outlaw':f.name}</span><strong className={hostile?'red':''}>{hostile?'Hostile':c.distressed?'Distress signal':game.relation(faction)}</strong></div>
 <CaptainPortrait contact={c} faction={faction}/>
 {world?<><div className="planet-dossier"><div className={`planet-portrait ${world.type}`} style={{'--planet-color':world.color} as React.CSSProperties}>{world.ring&&<i/>}</div><div><span className="eyebrow">{world.type.toUpperCase()} WORLD</span><h3>{world.economy}</h3><dl><div><dt>Population</dt><dd>{world.population}</dd></div><div><dt>Atmosphere distance</dt><dd>{Math.max(0,Math.round(dist-world.radius))} m</dd></div><div><dt>Survey</dt><dd>{game.s.surveyed?.includes(world.id)?'Complete':'Uncharted'}</dd></div></dl></div></div><div className="interaction-actions"><button className="primary" onClick={approach}><Navigation size={16}/>Enter orbit</button><button className="secondary" disabled={!surveyRange||game.s.surveyed?.includes(world.id)} onClick={()=>game.scanPlanet(world.id)}><ScanLine size={16}/>{game.s.surveyed?.includes(world.id)?'Surveyed':'Survey · +350 cr'}</button>{world.inhabited?<button className="secondary" disabled={!inOrbit||game.availableCargo(3)<3||cooldown>0} onClick={()=>game.planetAction(world.id,'aid')}><HeartPulse size={16}/>Medical aid · 3 t · +8 standing</button>:<button className="secondary" disabled={!inOrbit||game.usedCargo+3>game.stats.cargo||cooldown>0} onClick={()=>game.planetAction(world.id,'mine')}><Gem size={16}/>Extract 3 t {GOODS[world.good].name.toLowerCase()}</button>}{world.type==='gas'&&<button className="secondary" disabled={!inOrbit||game.s.fuel>=100||cooldown>0} onClick={()=>game.planetAction(world.id,'fuel')}><Fuel size={16}/>Skim +20 fuel</button>}{world.inhabited&&<button className="secondary" disabled={!game.dockingAllowed} onClick={dock}><Orbit size={16}/>Request station berth <ArrowUpRight size={15}/></button>}</div>{cooldown>0&&<p className="comms-status">Shuttle recharge · {cooldown}s of flight</p>}{!inOrbit&&<p className="comms-status">Surface operations within 350 m · survey within 500 m</p>}</>
 :c.kind==='station'&&c.id!=='station'?<><div className="authority-dossier"><Orbit size={46}/><h3>{c.role==='blockade'?'Jump corridor interdicted':'Planetary defence command'}</h3><p>{c.role==='blockade'?'Destroy this station to reopen the blocked route.':'Three-missile salvos · automatic point defence'}</p></div><div className="interaction-actions"><button className="secondary" onClick={approach}>Approach</button><button className="danger" onClick={()=>{close();game.paused=false;game.fire();if(game.s.weapon==='phaser')game.beamTrigger=.25;}}>Fire selected weapon</button></div></>:c.kind==='station'?<><div className="authority-dossier"><Orbit size={68}/><h3>{game.dockingAllowed?'Berth clearance available':game.standing()<0?'Faction exclusion order':'Security lockdown'}</h3><p>{SYSTEMS[game.s.system].kind} · {game.relation()} · standing {game.standing()}</p></div><div className="interaction-actions"><button className="primary" disabled={!game.dockingAllowed} onClick={dock}>Approach & dock</button>{!!incident?.fine&&<button className="secondary" disabled={game.s.credits<incident.fine} onClick={()=>game.payFine()}>Pay fine · {incident.fine.toLocaleString()} cr</button>}</div>{game.standing()<0&&<p className="comms-status">Medical aid and pirate bounties can restore standing. Paying a fine clears the local alert.</p>}</>
 :<><div className="ship-dossier"><ShipPortrait ship={c.ship??'courier'}/><div><span className="eyebrow">{c.kind==='trader'?'CIVILIAN VESSEL':c.kind==='patrol'?'SYSTEM SECURITY':'OUTLAW'}</span><h3>{SHIPS[c.ship??'courier'].name} class</h3><dl><div><dt>Hull</dt><dd>{Math.ceil(c.hull)} / {c.maxHull}</dd></div><div><dt>Shields</dt><dd>{Math.ceil(c.shield)}</dd></div><div><dt>Range</dt><dd>{Math.round(dist)} m</dd></div><div><dt>Weapons</dt><dd>{WEAPONS[SHIPS[c.ship??'courier'].weapon].name}</dd></div></dl></div></div><div className="comms-line"><Radio size={17}/>{c.kind==='trader'?(refusing?'Mayday. Security notified. Keep your distance.':'Channel open. Ready for cargo transfer.'):hostile?'Weapons lock confirmed. Break off immediately.':'Patrol channel open. Keep the trade lanes clear.'}</div><div className="interaction-actions"><button className="primary" onClick={approach}><Navigation size={16}/>Intercept</button><button className="danger" onClick={()=>{close();game.paused=false;game.fire();}}><Crosshair size={16}/>{hostile||c.role==='invader'?'Fire selected weapon':'Attack · −12 standing'}</button>{c.kind==='patrol'&&!!incident?.fine&&<button className="secondary" disabled={game.s.credits<incident.fine} onClick={()=>game.payFine()}>Pay fine · {incident.fine.toLocaleString()} cr</button>}</div>{c.kind==='trader'&&<div className="civilian-market"><div className="section-title"><span>CARGO TRANSFER</span><span>{Math.round(dist)} / 300 m</span></div><div className="civilian-stock"><Package size={21}/><div><strong>{GOODS[good].name}</strong><small>{stock} t available · {buyPrice} cr/t</small></div><button className="secondary" disabled={!!refusing||dist>300||stock<1||game.s.credits<buyPrice||game.usedCargo>=game.stats.cargo} onClick={()=>game.civilianTrade(c.id,good,1,true)}>Buy 1 t</button></div>{GOODS.map((g,i)=>game.availableCargo(i)>0&&<div className="civilian-stock" key={g.name}><span>{g.name}</span><small>{Math.floor(game.price[i]*.78)} cr/t</small><button className="secondary" disabled={!!refusing||dist>300} onClick={()=>game.civilianTrade(c.id,i,1,false)}>Sell 1 t</button></div>)}</div>}</>}
 </div>;
}
