'use client';
import { Radio,Shield,Crosshair,Navigation,Orbit,Zap,Target } from 'lucide-react';
import {Universe,SYSTEMS,FACTIONS,supportsPointDefense,supportsAntimatter,ANTIMATTER_DEPOTS} from './engine';
import {EVENT_NAMES,conditionAt} from './galaxy';
import {PanelHeader} from './Panels';
import FactionFlag from './FactionFlag';

export function GalacticNews({game,close}:{game:Universe;close:()=>void}){
 const galaxy=game.s.galaxy!;
 return <div className="workspace-overlay news-workspace"><PanelHeader eyebrow="SUBSPACE NETWORK" title="A galaxy in motion" close={close}/><div className="war-fronts">{galaxy.wars.map(w=><article className="war-front" key={w.id}><div><FactionFlag faction={w.attacker}/><Crosshair size={16}/><FactionFlag faction={w.defender}/><span>ACTIVE WAR</span></div><h3>{FACTIONS[w.attacker].short} <small>vs</small> {FACTIONS[w.defender].short}</h3><p>Front: {SYSTEMS[w.front].name}</p><div className="war-pressure"><i style={{width:`${Math.max(0,Math.min(100,w.pressure))}%`}}/></div><span>{Math.round(w.pressure)}% assault pressure · next offensive in {Math.max(0,Math.ceil(w.next-game.s.time))}s</span></article>)}</div><div className="subheading"><h3>Developing situations</h3><span>48 systems · 240 worlds</span></div><div className="situation-list">{SYSTEMS.filter(s=>conditionAt(game,s.id)).map(s=>{const c=conditionAt(game,s.id)!;return <div key={s.id}><span className={`event-mark ${c.kind}`}/><div><strong>{s.name}</strong><span>{EVENT_NAMES[c.kind]}{c.route!==undefined?' · '+SYSTEMS[c.route].name+' lane':''}</span></div><small>{Math.ceil((c.until-game.s.time)/60)} min</small>{s.id===game.s.system&&['blockade','siege','relic'].includes(c.kind)&&<button className="secondary" onClick={()=>{const target=game.contacts.find(x=>x.encounter===c.serial&&(x.role==='blockade'||x.role==='invader'||x.role==='relic'));if(target){game.target=target.id;game.waypoint={x:target.x,y:target.y};game.autoDock=false;}close();}}><Target size={14}/>Locate</button>}</div>;})}</div><div className="subheading"><h3>Dispatches</h3><span>Flight time</span></div><div className="dispatch-list">{galaxy.news.map(n=><article key={n.id}><time>{Math.floor(n.time/60)}:{String(n.time%60).padStart(2,'0')}</time><div><span>{SYSTEMS[n.system].name}</span><p>{n.text}</p></div></article>)}</div></div>;
}
export function WorldTicker({game,open}:{game:Universe;open:()=>void}){
 const c=game.condition,latest=game.s.galaxy!.news[0];
 return <button className={`world-ticker ${c?.kind??''}`} onClick={open}><Radio size={15}/><span>{c?EVENT_NAMES[c.kind]:game.s.galaxy!.wars.length+' galactic wars'}<small>{latest?SYSTEMS[latest.system].name+' · '+latest.text:'Subspace network online'}</small></span><span className="ticker-arrow">↗</span></button>;
}
export function EquipmentShop({game}:{game:Universe}){
 const eq=game.s.equipment!,pd=supportsPointDefense(game.s.ship),am=supportsAntimatter(game.s.ship),depot=game.s.galaxy!.rare[game.s.system],allied=game.standing()>=50,cost=(eq.pointDefense+1)*4500;
 return <><div className="subheading"><h3>Special systems</h3><span>Ship compatibility applies</span></div><div className="equipment-grid"><article><Shield size={25}/><h4>Point defence</h4><p>Automatically intercepts missiles. 5 energy per shot.</p><span>{pd?'Compatible · level '+eq.pointDefense+' / 2':'Requires a supported freighter or cruiser'}</span><button className="secondary" disabled={!pd||eq.pointDefense>=2||game.s.credits<cost} onClick={()=>game.installEquipment('pointDefense')}>{eq.pointDefense===2?'Fully upgraded':!pd?'Incompatible hull':cost.toLocaleString()+' cr'}</button></article><article className="antimatter-equipment"><Orbit size={25}/><h4>Antimatter launcher</h4><p>Creates a 350 m singularity. Ships and stations caught inside are annihilated.</p><span>{eq.antimatter?'Installed · '+eq.ammo+' / 3 warheads':!am?'Requires a cruiser or capital ship':!depot?'Rare depots: Halo, Aurelia, Talassa Gate, Triton':'Allied standing required · stock '+depot.stock}</span>{!eq.antimatter?<button className="secondary" disabled={!am||!depot?.stock||!allied||game.s.credits<32000} onClick={()=>game.installEquipment('antimatter')}>Install + 1 warhead · 32,000 cr</button>:<button className="secondary" disabled={!depot?.stock||!allied||eq.ammo>=3||game.s.credits<8500} onClick={()=>game.buyAntimatter()}>Warhead · 8,500 cr {depot?'· '+depot.stock+' in stock':''}</button>}</article></div></>;
}
