'use client';
import { useEffect, useRef, useState, useId } from 'react';
import { X, ArrowUpRight, ArrowRight, ArrowDownLeft, Wheat, Gem, Cpu, HeartPulse, Boxes, Wrench, Rocket, Crosshair, Compass, Shield, Zap, Package, Check, Fuel, Orbit, Anchor, Cookie, Download, Upload, AlertTriangle } from 'lucide-react';
import { Universe, SYSTEMS, GOODS, SHIPS, FACTIONS, factionIds, fleetFor, type ShipClass, type GameState, type Contract, systemDistance, fuelCost, initialState } from './engine';
import FactionFlag from './FactionFlag';
import ShipPortrait from './ShipPortrait';
import { encodeSave } from './cookies';
const fmt = (n: number) => Math.round(n).toLocaleString();
const icons = [Wheat, Boxes, Cpu, HeartPulse, Gem, Wrench];
export const PAGES_URL = 'https://samcousinsgb.github.io/voidwake/';

export function PanelHeader({ eyebrow, title, close }: { eyebrow: string; title: string; close: () => void }) {
  const ref = useRef<HTMLDivElement>(null); const id = useId();
  useEffect(() => {
    const panel = ref.current?.closest('.workspace-overlay') as HTMLElement | null;
    if (!panel) return;
    panel.setAttribute('role', 'dialog'); panel.setAttribute('aria-modal', 'true'); panel.setAttribute('aria-labelledby', id);
    const previous = document.activeElement as HTMLElement | null;
    panel.querySelector<HTMLButtonElement>('button')?.focus({ preventScroll: true });
    const trap = (e: KeyboardEvent) => {
      const overlays = document.querySelectorAll('.workspace-overlay');
      if (e.key !== 'Tab' || overlays[overlays.length - 1] !== panel) return;
      const items = [...panel.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not([type=hidden]),[tabindex="0"]')].filter(el => el.getClientRects().length > 0);
      if (!items.length) return;
      const first = items[0], last = items[items.length - 1];
      if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
      if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    };
    document.addEventListener('keydown', trap);
    return () => { document.removeEventListener('keydown', trap); if (previous?.isConnected) previous.focus({ preventScroll: true }); };
  }, [id]);
  return <div className="panel-heading" ref={ref}><div><div className="eyebrow">{eyebrow}</div><h2 id={id}>{title}</h2></div><button className="close-button" aria-label="Close panel" onClick={close}><X size={20}/></button></div>;
}

export function GalaxyMap({ game, close }: { game: Universe; close: () => void }) {
  const [destination, setDestination] = useState((game.s.system + 1) % SYSTEMS.length);
  const from = SYSTEMS[game.s.system], to = SYSTEMS[destination], dist = systemDistance(from.id, to.id), cost = fuelCost(from.id, to.id);
  const reachable = dist <= 5.8 && from.id !== to.id, enough = game.s.fuel >= cost;
  return <div className="workspace-overlay map-workspace"><PanelHeader eyebrow="NAVIGATION" title="The Outer Reach" close={close}/>
    <div className="expanded-galaxy"><svg viewBox="0 0 1100 760" aria-label="24-system galaxy map"><defs><pattern id="mapgrid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#253c51" strokeWidth=".6"/></pattern></defs><rect width="1100" height="760" fill="url(#mapgrid)"/>
    {SYSTEMS.flatMap((a,i)=>SYSTEMS.filter(b=>b.id>i&&systemDistance(a.id,b.id)<=5.8).map(b=><line key={a.id+'-'+b.id} x1={a.x*6} y1={a.y*5.2} x2={b.x*6} y2={b.y*5.2} stroke={a.id===from.id||b.id===from.id?'#65859c':'#263b4c'} strokeDasharray="3 7"/>))}
    {SYSTEMS.map(sys=><g key={sys.id} className="map-system" role="button" tabIndex={0} aria-label={sys.name+', '+sys.faction+', '+game.relation(sys.factionId)} onClick={()=>setDestination(sys.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setDestination(sys.id);}}} transform={`translate(${sys.x*6} ${sys.y*5.2})`}><circle r="32" fill="transparent"/><circle r="25" fill={FACTIONS[sys.factionId].color} opacity=".05"/>{sys.id===destination&&<circle r="18" fill="none" stroke="#edfaff"/>}{sys.id===from.id&&<circle r="12" fill="none" stroke="#b1efd1" strokeDasharray="2 3"/>}<circle r="5" fill={game.standing(sys.factionId)<0?'#ff716b':FACTIONS[sys.factionId].color}/><text y="39" textAnchor="middle" fill={sys.id===destination?'#fff':'#bed0dc'} fontSize="16">{sys.name}</text></g>)}</svg></div>
    <div className="system-catalog">{factionIds.map(id=><div key={id}><div><FactionFlag faction={id}/><span>{FACTIONS[id].short}</span></div>{SYSTEMS.filter(sys=>sys.factionId===id).map(sys=><button key={sys.id} className={destination===sys.id?'selected':''} onClick={()=>setDestination(sys.id)}>{sys.name}{sys.id===from.id?<span>Here</span>:game.standing(id)<0?<span className="red">Hostile</span>:systemDistance(from.id,sys.id)<=5.8?<span>{fuelCost(from.id,sys.id)} fuel</span>:null}</button>)}</div>)}</div>
    <div className="destination-card"><div><span className={`risk-badge risk-${to.risk}`}>{to.security}</span><h3>{to.name}<small>{to.kind}</small></h3><p>{to.station} · {game.relation(to.factionId)}</p></div><div className="jump-details"><div><span>DISTANCE</span><strong>{dist.toFixed(1)} <small>ly</small></strong></div><div><span>FUEL</span><strong className={!enough ? 'red' : ''}>{cost} <small>/ {Math.floor(game.s.fuel)}</small></strong></div></div><button className="primary" disabled={!reachable || !enough} onClick={() => { if (game.docked) game.undock(); if (game.startJump(to.id)) close(); }}><Zap size={15}/>{from.id === to.id ? 'Current system' : !reachable ? 'Out of range' : !enough ? 'Insufficient fuel' : game.docked ? 'Undock & jump' : 'Jump'}<ArrowUpRight size={15}/></button></div>
    <div className="map-market"><div className="section-title"><span>Trade margins</span><span>{from.name} → {to.name} · cr/t</span></div><div className="price-preview">{GOODS.map((g, i) => { const current = from.prices[i], sell = Math.floor(to.prices[i] * .85), profit = sell - current; return <div key={g.name}><span>{g.name}</span><strong>{current} <ArrowRight size={11}/> {sell}<small className={profit > 0 ? 'green' : 'dim'}>{profit > 0 ? '+' : ''}{profit}</small></strong></div>; })}</div></div>
  </div>;
}

function Market({ game }: { game: Universe }) {
  const [quantity, setQuantity] = useState<number | 'max'>(5); const [error, setError] = useState('');
  const amount = (good: number, buy: boolean) => quantity === 'max' ? buy ? Math.max(0, Math.min(game.stock[good], game.stats.cargo - game.usedCargo, Math.floor(game.s.credits / game.price[good]))) : game.availableCargo(good) : quantity;
  const trade = (good: number, buy: boolean) => { const result = game.trade(good, amount(good, buy), buy); setError(result.ok ? '' : result.message); };
  return <><div className="market-summary"><div className="station-balance"><Package size={16}/><span>{game.usedCargo} / {game.stats.cargo} t</span></div><div className="quantity-picker"><span>TONNES</span>{([1, 5, 10, 'max'] as const).map(q => <button key={q} className={quantity === q ? 'chosen' : ''} aria-pressed={quantity === q} onClick={() => setQuantity(q)}>{q === 'max' ? 'Max' : q}</button>)}</div></div>
    <div className="market-table"><div className="market-row table-head"><span>COMMODITY</span><span>STOCK</span><span>HOLD</span><span>BUY cr/t</span><span>SELL cr/t</span><span/></div>{GOODS.map((g, i) => { const Icon = icons[i], buy = game.price[i], sell = Math.floor(buy * .85), buyAmount = amount(i, true), sellAmount = amount(i, false); return <div className="market-row" key={g.name}><div className="commodity"><Icon size={22}/><span>{g.name}{game.reservedCargo(i) > 0 && <small>{game.reservedCargo(i)} t reserved</small>}</span></div><span className="dim">{game.stock[i]}</span><span>{game.s.cargo[i]}</span><strong>{buy}</strong><strong>{sell}</strong><div className="trade-actions"><button aria-label={`Buy ${buyAmount} tonnes of ${g.name} for ${buy * buyAmount} credits`} title={`${buyAmount} t · ${fmt(buy * buyAmount)} cr`} disabled={buyAmount < 1 || game.s.credits < buy * buyAmount || game.usedCargo + buyAmount > game.stats.cargo || game.stock[i] < buyAmount} onClick={() => trade(i, true)}><ArrowDownLeft size={13}/>Buy</button><button aria-label={`Sell ${sellAmount} tonnes of ${g.name} for ${sell * sellAmount} credits`} title={`${sellAmount} t · ${fmt(sell * sellAmount)} cr`} disabled={sellAmount < 1 || game.availableCargo(i) < sellAmount} onClick={() => trade(i, false)}><ArrowUpRight size={13}/>Sell</button></div></div>; })}</div>
    {error && <p className="inline-error" role="alert">{error}</p>}
  </>;
}

function Shipyard({ game }: { game: Universe }) {
  const upgrades: { key: keyof GameState['upgrades']; name: string; desc: string; price: number; icon: typeof Zap }[] = [{ key: 'weapon', name: 'Weapons amplifier', desc: '+8 damage', price: 900, icon: Crosshair }, { key: 'shield', name: 'Shield harmonics', desc: '+40 shields', price: 750, icon: Shield }, { key: 'engine', name: 'Impulse tuning', desc: '+25 m/s', price: 650, icon: Zap }, { key: 'cargo', name: 'Cargo expansion', desc: '+15 t', price: 600, icon: Package }];
  return <><div className="subheading"><h3>Upgrades</h3></div><div className="upgrade-grid">{upgrades.map(u => { const level = game.s.upgrades[u.key], cost = u.price * (level + 1), Icon = u.icon; return <div className="upgrade-card" key={u.key}><div><Icon size={23}/><span>{level} / 3</span></div><h4>{u.name}</h4><p>{u.desc}</p><button className="secondary" disabled={level >= 3 || game.s.credits < cost} onClick={() => game.upgrade(u.key)}>{level >= 3 ? <><Check size={14}/> Maxed</> : `${fmt(cost)} cr`}</button></div>; })}</div><div className="subheading"><h3>Ships</h3></div><div className="shipyard-ships">{(Object.entries(SHIPS) as [ShipClass, typeof SHIPS.courier][]).filter(([id,ship])=>ship.faction===game.faction||id==='courier'||id==='freighter').map(([id, ship]) => <div className={`ship-option ${game.s.ship === id ? 'owned' : ''}`} key={id}><ShipPortrait ship={id}/><FactionFlag faction={ship.faction}/><h4>{ship.name}</h4><p>{ship.role}</p><div><span>{ship.hull} hull</span><span>{ship.cargo} t</span><span>{ship.speed} m/s</span></div><button className="secondary" disabled={!game.shipAvailable(id) || game.s.ship === id || game.s.credits < ship.price || game.usedCargo > ship.cargo + game.s.upgrades.cargo * 15} onClick={() => game.buyShip(id)}>{game.s.ship === id ? 'Current ship' : !game.shipAvailable(id)?'Allied standing · 50 required' : game.usedCargo > ship.cargo + game.s.upgrades.cargo * 15 ? 'Cargo exceeds capacity' : ship.price ? `${fmt(ship.price)} cr` : 'Free'}</button></div>)}</div></>;
}

function ContractCard({ c, game, offer = false }: { c: Contract; game: Universe; offer?: boolean }) {
  const ready = c.type === 'delivery' ? game.s.system === c.target && game.s.cargo[c.good!] >= c.quantity : c.type === 'bounty' ? c.progress >= c.quantity && game.s.system === c.origin : game.s.system === c.target;
  const Icon = c.type === 'delivery' ? Package : c.type === 'bounty' ? Crosshair : Compass;
  return <div className="contract-card"><div className="contract-title"><Icon size={22}/><div><span>{c.type === 'delivery' ? 'FREIGHT' : c.type === 'bounty' ? 'BOUNTY' : 'SURVEY'}</span><h4>{c.title}</h4></div><strong>{fmt(c.reward)}<small>cr</small></strong></div>
    <div className="contract-route"><span>{c.type === 'delivery' ? `${c.quantity} t ${GOODS[c.good!].name.toLowerCase()}` : c.type === 'bounty' ? `${c.quantity} pirates in ${SYSTEMS[c.target].name}` : 'Survey data'}</span><ArrowRight size={14}/><strong>{SYSTEMS[c.type === 'bounty' ? c.origin : c.target].station}</strong></div>
    <div className="contract-bottom">{offer ? <><span>{c.type === 'delivery' ? 'Shipment supplied' : SYSTEMS[c.target].security}</span><button className="secondary" disabled={game.s.contracts.filter(c => !c.done).length >= 3 || (c.type === 'delivery' && game.stats.cargo - game.usedCargo < c.quantity)} onClick={() => game.accept(c.id)}>Accept <ArrowUpRight size={14}/></button></> : c.done ? <span className="green"><Check size={14}/> Paid</span> : <><span>{c.type === 'bounty' ? `${Math.min(c.progress, c.quantity)} / ${c.quantity} destroyed` : ready ? 'Ready to deliver' : SYSTEMS[c.target].name}</span><div><button className="abandon" onClick={() => game.cancelContract(c.id)}>Abandon</button><button className="secondary" disabled={!ready || !game.docked} onClick={() => game.complete(c.id)}>Claim reward</button></div></>}</div>
  </div>;
}

export function Contracts({ game, offers = true }: { game: Universe; offers?: boolean }) {
  const active = game.s.contracts.filter(c => !c.done);
  return <><div className="subheading"><h3>Active</h3><span>{active.length} / 3</span></div>{active.length ? active.map(c => <ContractCard key={c.id} c={c} game={game}/>) : <div className="empty-state"><Compass size={23}/><p>No active contracts</p></div>}{offers && <><div className="subheading"><h3>Available</h3></div>{game.offers.length ? game.offers.map(c => <ContractCard key={c.id} c={c} game={game} offer/>) : <div className="empty-state"><Check size={23}/><p>No contracts available</p></div>}</>}</>;
}

export function StationPanel({ game, close }: { game: Universe; close: () => void }) {
  const [view, setView] = useState('market'); const repair = Math.ceil(game.stats.hull - game.s.hull) * 3, fuel = Math.ceil(100 - game.s.fuel) * 4;
  return <div className="workspace-overlay station-workspace"><PanelHeader eyebrow={`${SYSTEMS[game.s.system].name.toUpperCase()} / STATION`} title={SYSTEMS[game.s.system].station} close={close}/><div className="station-faction"><FactionFlag faction={game.faction}/>{FACTIONS[game.faction].name}<span>{game.relation()} · {game.standing()}</span></div><div className="station-topline"><span><span className="live-dot"/> Docked</span><strong>{fmt(game.s.credits)}<small>cr</small></strong></div><div className="station-tabs">{[{ id: 'market', name: 'Market', icon: Boxes }, { id: 'shipyard', name: 'Shipyard', icon: Wrench }, { id: 'contracts', name: 'Contracts', icon: Compass }].map(({ id, name, icon: Icon }) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon size={16}/>{name}{id === 'contracts' && game.s.contracts.some(c => !c.done) && <i/>}</button>)}</div><div className="station-content">{view === 'market' ? <Market game={game}/> : view === 'shipyard' ? <Shipyard game={game}/> : <Contracts game={game}/>}</div><div className="station-services"><button className="secondary" disabled={repair === 0 || game.s.credits < repair} onClick={() => game.service('repair')}><Wrench size={14}/>{repair === 0 ? 'Hull intact' : `Repair · ${fmt(repair)} cr`}</button><button className="secondary" disabled={fuel === 0 || game.s.credits < fuel} onClick={() => game.service('fuel')}><Fuel size={14}/>{fuel === 0 ? 'Fuel full' : `Refuel · ${fmt(fuel)} cr`}</button><button className="primary" onClick={close}>Undock <ArrowUpRight size={15}/></button></div></div>;
}

export function CargoPanel({ game, close }: { game: Universe; close: () => void }) {
  return <div className="workspace-overlay"><PanelHeader eyebrow={game.stats.name.toUpperCase()} title="Cargo" close={close}/><div className="cargo-overview"><Package size={35}/><div><strong>{game.usedCargo}<small>/ {game.stats.cargo} t</small></strong></div></div><div className="cargo-load-bar"><i style={{ width: `${game.usedCargo / game.stats.cargo * 100}%` }}/></div>{game.usedCargo ? GOODS.map((g, i) => game.s.cargo[i] > 0 && <div key={g.name} className="manifest-row"><span>{g.name}{game.reservedCargo(i) > 0 && <small>{game.reservedCargo(i)} t reserved</small>}</span><strong>{game.s.cargo[i]} t</strong><span>{fmt(game.s.cargo[i] * Math.floor(game.price[i] * .85))} cr<small>Resale in {SYSTEMS[game.s.system].name}</small></span></div>) : <div className="empty-state large"><Boxes size={30}/><p>Hold empty</p></div>}<div className="manual-bottom"><button className="primary" onClick={() => { close(); game.dock(); }}><Anchor size={15}/>{game.docked ? 'Station market' : 'Approach station'}</button></div></div>;
}

export function LogPanel({ game, close }: { game: Universe; close: () => void }) {
  const [confirmReset, setConfirmReset] = useState(false); const [imported, setImported] = useState<GameState | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  const exportSave = () => { game.save(); const blob = new Blob([JSON.stringify(game.s)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'voidwake-save.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const transferSave = () => { game.save(); window.location.assign(`${PAGES_URL}#save=${encodeSave(game.s)}`); };
  const applyImported = () => { if (!imported) return; game.s = imported; game.docked = !!imported.docked; game.waypoint = null; game.jump = null; game.autoDock = false; game.populate(); game.onRestore(); const ok = game.save(); game.notify(ok ? 'Save imported.' : 'Imported. Cookies are blocked.', ok ? 'info' : 'error'); setImported(null); close(); };
  return <div className="workspace-overlay"><PanelHeader eyebrow="CAPTAIN’S LOG" title="Flight record" close={close}/><div className="record-grid"><div><span>SYSTEMS</span><strong>{game.s.visited.length}<small>/ {SYSTEMS.length}</small></strong></div><div><span>KILLS</span><strong>{game.s.kills}</strong></div><div><span>CONTRACTS</span><strong>{game.s.completed.length}</strong></div><div><span>REPUTATION</span><strong>{game.s.reputation < 10 ? 'Independent' : game.s.reputation < 35 ? 'Trusted' : 'Distinguished'}</strong></div></div><Contracts game={game} offers={false}/><div className="subheading"><h3>Visited</h3><span>{Math.floor(game.s.time / 60)} min</span></div><div className="visited-list">{game.s.visited.map(id => <div key={id}><Orbit size={16}/><span>{SYSTEMS[id].name}</span><small>{SYSTEMS[id].faction}</small><Check size={14}/></div>)}</div><div className="save-info"><Cookie size={19}/><p className={game.saveStatus === 'blocked' ? 'red' : ''}>{game.saveStatus === 'blocked' ? 'Cookies blocked' : 'Saved in cookies'}<small>{game.saveStatus === 'blocked' ? 'Allow cookies or export your progress.' : 'This browser · 1 year'}</small></p><button className="secondary" onClick={() => { const ok = game.save(); game.notify(ok ? 'Saved.' : 'Cookies are blocked.', ok ? 'info' : 'error'); }}>Save</button></div><div className="save-actions"><button className="secondary" onClick={exportSave}><Download size={14}/>Export</button><button className="secondary" onClick={() => inputRef.current?.click()}><Upload size={14}/>Import</button><input ref={inputRef} type="file" accept=".json,application/json" aria-label="Import saved game" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 50000) throw new Error(); const state = Universe.validate(JSON.parse(await file.text())); if (!state) throw new Error(); setImported(state); } catch { game.notify('Invalid save file.', 'error'); } e.target.value = ''; }}/>{typeof window !== 'undefined' && window.location.hostname !== 'samcousinsgb.github.io' && <button className="secondary" onClick={transferSave}>Continue on GitHub Pages <ArrowUpRight size={14}/></button>}</div>
    {imported && <div className="reset-confirm"><p>Replace this voyage with {imported.ship} · {fmt(imported.credits)} cr · {SYSTEMS[imported.system].name}?</p><button className="primary" onClick={applyImported}>Import save</button><button className="secondary" onClick={() => setImported(null)}>Cancel</button></div>}
    {confirmReset ? <div className="reset-confirm"><p>Replace this save with a new voyage?</p><button className="danger" onClick={() => { const prefs = game.s.preferences; game.s = initialState(); game.s.preferences = prefs; game.docked = false; game.waypoint = null; game.jump = null; game.autoDock = false; game.populate(); game.save(); close(); }}>New voyage</button><button className="secondary" onClick={() => setConfirmReset(false)}>Cancel</button></div> : <button className="subtle-button" onClick={() => setConfirmReset(true)}>New voyage</button>}
  </div>;
}

export function FlightManual({ game, close }: { game: Universe; close: () => void }) {
  return <div className="workspace-overlay"><PanelHeader eyebrow="FLIGHT" title="Controls" close={close}/><div className="control-grid">{[['W / ↑', 'Thrust'], ['A D / ← →', 'Steer'], ['S / ↓', 'Brake'], ['SHIFT', 'Boost'], ['SPACE', 'Fire selected weapon'], ['1–4', 'Select weapon'], ['H', 'Hail target'], ['T', 'Cycle target'], ['E', 'Approach & dock'], ['M', 'Galaxy map'], ['ESC', 'Pause / close'], ['CLICK', 'Select / autopilot'], ['SCROLL', 'Zoom']].map(([key, label]) => <div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div><div className="record-grid"><div><span>AUTO-AIM</span><strong>760–1800<small>m</small></strong></div><div><span>SHIELD RECHARGE</span><strong>4<small>s</small></strong></div><div><span>SALVAGE RANGE</span><strong>65<small>m</small></strong></div><div><span>RESCUE FEE</span><strong>10<small>% + cargo</small></strong></div></div><div className="manual-bottom"><button className="secondary" onClick={() => { close(); game.emergencyTow(); }}><Wrench size={15}/> Tow to station · up to 250 cr</button><button className="primary" onClick={close}>Return <ArrowUpRight size={15}/></button></div></div>;
}
