import type { Universe } from './engine';
type Tool = {name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
type ModelContext = {registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>};
function object(input:unknown):Record<string,unknown>{if(input===null||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object.');return input as Record<string,unknown>;}
export function gameTools(game:Universe,refresh:()=>void):Tool[]{return [
 {name:'get_flight_status',title:'Read flight status',description:'Read current system ID, ship, credits, cargo, fuel, docking state, and active contracts. System IDs are 0 Solace, 1 Cinder, 2 Vesper, 3 Aster, 4 Nyx, 5 Kestrel, 6 Halo.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({system:game.s.system,ship:game.s.ship,credits:game.s.credits,fuel:game.s.fuel,hull:game.s.hull,shield:game.s.shield,docked:game.docked,cargo:[...game.s.cargo],capacity:game.stats.cargo,contracts:game.s.contracts.map(c=>({...c}))})},
 {name:'trade_commodity',title:'Buy or sell cargo',description:'Complete a commodity purchase or sale at the current docked station. IDs: 0 food, 1 titanium, 2 microcircuits, 3 medicine, 4 void crystals, 5 ship parts. Refuses trades when undocked, unaffordable, beyond capacity, or involving reserved contract cargo.',inputSchema:{type:'object',properties:{commodity:{type:'integer',minimum:0,maximum:5},tonnes:{type:'integer',minimum:1,maximum:135},side:{type:'string',enum:['buy','sell']}},required:['commodity','tonnes','side'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{const v=object(input);if(!Number.isInteger(v.commodity)||!Number.isInteger(v.tonnes)||(v.side!=='buy'&&v.side!=='sell'))throw new Error('A valid commodity, whole tonnes, and buy/sell side are required.');const result=game.trade(v.commodity as number,v.tonnes as number,v.side==='buy');refresh();return {...result,credits:game.s.credits,cargo:[...game.s.cargo]};}},
 {name:'start_station_approach',title:'Approach and dock',description:'Start autopilot to the system station. If within docking range, dock immediately and open the station. Does not teleport or skip flight.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(game.paused||game.jump!==null)return {ok:false,message:'Return to unpaused flight before approaching a station.'};game.dock();refresh();return {ok:true,docked:game.docked,autopilot:game.autoDock};}},
 ];}
export function registerGameTools(game:Universe,refresh:()=>void){const context=typeof document==='undefined'?undefined:(document as unknown as {modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return ()=>{};const lifecycle=new AbortController();for(const tool of gameTools(game,refresh)){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* WebMCP is optional; native game controls remain available. */}}return ()=>lifecycle.abort();}
